# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ROI Analyze app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Install workspace dependencies
        run: |
          npm install --workspace=packages/backend
          npm install --workspace=packages/client

      - name: Build for Azure deployment
        run: |
          chmod +x ./build-for-azure-simple.sh
          ./build-for-azure-simple.sh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: roianalyze-app
          path: azure-deploy/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: roianalyze-app
          path: azure-deploy/
      - name: List downloaded files
        run: |
          echo "=== Downloaded files ==="
          ls -la
          echo "=== Dist directory ==="
          ls -la dist/ || echo "No dist directory"
          echo "=== Public directory ==="
          ls -la public/ || echo "No public directory"
          echo "=== Check for server.js ==="
          ls -la server.js || echo "No server.js file"
          echo "=== Check for package.json ==="
          ls -la package.json || echo "No package.json file"

      - name: Install production dependencies
        run: |
          npm install --omit=dev

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5FE90FB5B9AC4A8F8EB40D0D63E6E5EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7AC8780C6F9E42C481AA94816382807D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F4035DFB0BF47AB933E8A73E7A445FE }}

      # Uncomment and configure the following step with your actual resource group name
      # - name: Configure Azure Web App settings
      #   run: |
      #     az webapp config appsettings set \
      #       --resource-group YOUR_RESOURCE_GROUP \
      #       --name cyfnodetest \
      #       --settings \
      #         NODE_ENV=production \
      #         PORT=8080 \
      #         WEBSITE_NODE_DEFAULT_VERSION=18-lts

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cyfnodetest'
          slot-name: 'Production'
          package: .

      - name: Verify deployment
        run: |
          echo "=== Deployment completed ==="
          echo "Health check URL: https://cyfnodetest.azurewebsites.net/health"
          echo "App URL: https://cyfnodetest.azurewebsites.net/"
          
          # Wait a bit for deployment to be ready
          sleep 30
          
          # Test health endpoint
          curl -f https://cyfnodetest.azurewebsites.net/health || echo "Health check failed - this is normal for first deployment"
